KyberNetwork/reserve-data

README.md
=> update readme - remove get open orders api

README.md, data/storage/ram_activity_storage.go
- Fix ram activities search index out of range
- Update readme api
=> update readme and fix index out of range

.gitignore, Dockerfile, README.md, blockchain/blockchain.go, cmd/dev.go, cmd/internal_mainnet.go, cmd/internal_mainnet_setting.json, cmd/main.go, common/token.go, common/util.go, data/storage/bolt.go, http/authentication.go, http/permission.go, http/server.go, metric/ram_storage.go, metric/storage.go, metric/types.go, signer/file_signer.go
API receive (set) target quantity from analytic and allow dashboard to get target quantity for all supported token.
@tranvictor  please review if it is reasonable or not.
=> Add token target quantity

README.md, common/types.go, exchange/binance.go, exchange/binance_format.go, exchange/bittrex.go, exchange/bittrex_format.go, http/server.go
- Add update binance notional limit for exchange info
- Update get exchange info for more flexible
=> Update binance notional limit

common/types.go, core/reserve_core.go
sanity check for deposit and withdraw via withdraw fee
=> add sanity check deposit, withdraw

cmd/main.go, vendor/github.com/robfig/cron/.gitignore, vendor/github.com/robfig/cron/.travis.yml, vendor/github.com/robfig/cron/LICENSE, vendor/github.com/robfig/cron/README.md, vendor/github.com/robfig/cron/constantdelay.go, vendor/github.com/robfig/cron/constantdelay_test.go, vendor/github.com/robfig/cron/cron.go, vendor/github.com/robfig/cron/cron_test.go, vendor/github.com/robfig/cron/doc.go, vendor/github.com/robfig/cron/parser.go, vendor/github.com/robfig/cron/parser_test.go, vendor/github.com/robfig/cron/spec.go, vendor/github.com/robfig/cron/spec_test.go, vendor/gopkg.in/natefinch/lumberjack.v2/.gitignore, vendor/gopkg.in/natefinch/lumberjack.v2/LICENSE, vendor/gopkg.in/natefinch/lumberjack.v2/README.md, vendor/gopkg.in/natefinch/lumberjack.v2/chown.go, vendor/gopkg.in/natefinch/lumberjack.v2/chown_linux.go, vendor/gopkg.in/natefinch/lumberjack.v2/example_test.go, vendor/gopkg.in/natefinch/lumberjack.v2/linux_test.go, vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack.go, vendor/gopkg.in/natefinch/lumberjack.v2/lumberjack_test.go, vendor/gopkg.in/natefinch/lumberjack.v2/rotate_test.go, vendor/gopkg.in/natefinch/lumberjack.v2/testing_test.go
- Rotate log using Lumberjack
- 24h hour log file
=> Add rotate log

cmd/configuration/exchanges.go, cmd/configuration/getconfig.go
Allow KyberENV to be switch to group the same setting paths environments.
Change all Huobi exchange object to asynchronous.
=> Update cli config

README.md, cmd/clicmd/startserver.go, cmd/configuration/config.go, common/types.go, http/server.go, interfaces.go, stat/analytic_storage.go, stat/reserve_stat.go, stat/storage/analytic_bolt.go, stat/storage/log_bolt.go
Add API endpoints for analytic to store/get price analytic data.
=> Price analytic data

README.md, common/types.go, data/reserve_data.go, data/storage.go, data/storage/bolt.go, http/server.go, interfaces.go, stat/fetcher.go
=> Failure resistance

exchange/binance.go
fix the skipping pair logic err
=> Binance batch querry

stat/fetcher.go, stat/stat_storage.go, stat/stat_storage_test_fw.go, stat/storage/stat_bolt.go, stat/storage/user_bolt.go, stat/user_storage.go
1. Optimize check kyced user
2. Fix user stat not consistent
3. Fix country heatmap load wrong
=> Update stats 

common/test_exchange.go, core/reserve_core_test.go, exchange/bittrex_test.go
- Add method get min deposit to test files
=> Fix test interface

stat/fetcher.go, stat/log_storage.go, stat/storage/log_bolt.go
- Separate Check Duplicate logs from Store logs logic
- Handle when Db op store logs failed.
=> Fix trade logs skipping at full storage

data/fetcher/fetcher.go, exchange/huobi.go, exchange/huobi/huobi_endpoint.go
ignore error on order status because analytic will cancel unfullfiled orders anw
=> ignore error on order status

README.md
[Go Report Card](https://goreportcard.com/report/github.com/KyberNetwork/reserve-data) is a free code quality  service for Golang.
=> Go report card

cmd/configuration/config.go, data/fetcher/fetcher_test.go, data/fetcher/http_runner/runner.go, data/fetcher/http_runner/runner_test.go, data/fetcher/http_runner/server.go
- added comment docs
- fix unhandled error
- remove the use of magic number
=> HttpRunner Start improvement

blockchain/gas_oracle.go
Merge back from master to develop in order to fix test failed.
=> Fix wrong gas station fetching

cmd/clicmd/startserver.go, cmd/clicmd/startserver_functions.go, data/reserve_data.go, http/http_test.go, http/server.go, interfaces.go
Move include exchanges into reserve data instead of put it in http object.
=> change exchange trade history

exchange/binance.go, exchange/binance/binance_bolt.go, exchange/binance/binance_bolt_test.go, exchange/binance_storage.go, exchange/bittrex/bittrex_bolt_test.go, exchange/huobi.go, exchange/huobi/bolt.go, exchange/huobi/huobi_bolt_test.go, exchange/huobi_storage.go
These test mostly focus on test storing exchange history.
=> Add test for exchange storage

README.md, cmd/clicmd/startserver.go, cmd/clicmd/startserver_functions.go, common/archive/aws.go, common/archive/s3.go
Fix Dirlog path error, update read me for aws config requirement
=> Fix s3 upload path

cmd/mainnet_setting.json
=> list-token-moc

stat/fetcher.go, stat/util/ip_locator.go
- Add more error log
- If country is empty, then set it to "unknown"
=> Add more error log

v3/http/asset_test.go, v3/http/assets.go, v3/http/exchanges.go, v3/http/http.go
consistent to response format.
=> use httputil to return response

v3/common/types.go, v3/http/asset_test.go, v3/http/http.go, v3/http/trading_pair_create.go, v3/http/trading_pair_test.go, v3/http/trading_pair_update.go, v3/storage/interface.go, v3/storage/postgres/assets.go, v3/storage/postgres/exchange_update.go, v3/storage/postgres/sql.go, v3/storage/postgres/trading_pair_create.go, v3/storage/postgres/trading_pair_update.go, v3/storage/postgres/trading_pairs.go
implement add/update trading pair
=> support create/update trading pair

cmd/configuration/flags.go, cmd/main.go
Current portFlag not allow core to bind to other host different from localhost which does not work with gateway. Change using listen flag.
=> Add listen flag, remove port flag

exchange/binance.go, exchange/huobi.go, reservesetting/storage/postgres/asset_exchange.go, reservesetting/storage/postgres/assets.go, reservesetting/storage/postgres/db_types.go, reservesetting/storage/postgres/setting_change_test.go, reservesetting/storage/postgres/setting_reader.go, reservesetting/storage/postgres/sql.go, v3/storage/postgres/db_types.go
- when deposit addr = null then return zero hex address
- usage of deposit address: right now only to filter address when fetch data from exchange
=> Refactor deposit address v3

common/exchange.go, common/test_exchange.go, core/reserve_core.go, core/reserve_core_test.go, exchange/binance.go, exchange/binance/mock/binance.go, exchange/huobi.go, exchange/huobi/huobi_endpoint.go, exchange/huobi_interface.go, exchange/stable_ex.go, http/server.go, interfaces.go
=> Refactor code

apidocs/source/includes/settings/_apis.md, apidocs/source/includes/settings/_create_asset.md, apidocs/source/includes/settings/_update_asset.md, reservesetting/common/types.go, reservesetting/http/setting_change_test.go, reservesetting/storage/postgres/assets.go, reservesetting/storage/postgres/assets_test.go, reservesetting/storage/postgres/setting_change.go, reservesetting/storage/postgres/setting_change_test.go, reservesetting/storage/postgres/setting_reader_test.go, reservesetting/storage/postgres/sql.go, reservesetting/storage/postgres/sql_schema.go
+ PriceUpdateThreshold float64
+ AskSpread float64
+ BidSpread float64
+ SingleFeedMaxSpread float64
+ MultipleFeedsMaxDiff float64
+ write a unit test for storage and http package
+ run the main and call the api directly
=>  add stable params field to asset

blockchain/blockchain.go, reservesetting/common/filter.go, reservesetting/common/types.go
* 5054 fetch balance all token - have address
* fetch rate with token have setrate only
=> 5054 fetch balance all token - have address (#761)

common/feeds.go, data/global_storage.go, data/reserve_data.go, data/storage/bolt.go, http/stable_exchanges.go, interfaces.go
Reverts KyberNetwork/reserve-data#784
=> Revert "add base_volatility_spread to feed_configuration"

data/fetcher/fetcher.go
* log tx hash when fetch tx status v1
=> log tx hash when fetch tx status v1 (#795)

apidocs/source/includes/exchanges/_exchanges.md, common/types.go, core/reserve_core.go, http/exchange_api.go, http/server.go, interfaces.go
* update docs and cancel order to accept multiple order ids
* update handle cancel orders
* update cancel order status success
* fix gocritic
* update cancel order response type
* update handle failed to get activity
=> Update docs and cancel order to accept multiple order ids (#870)

apidocs/source/includes/exchanges/_exchanges.md, core/reserve_core.go, exchange/binance.go, exchange/huobi.go, http/exchange_api.go, http/server.go, interfaces.go
=> Update api docs

apidocs/source/includes/exchanges/_exchanges.md, common/exchange.go, common/test_exchange.go, core/reserve_core_test.go, exchange/binance.go, exchange/binance/binance_endpoint.go, exchange/binance/mock/binance.go, exchange/binance_format.go, exchange/binance_interface.go, exchange/binance_live.go, exchange/binance_test.go, exchange/huobi.go, http/exchange_api.go
- Update `quotePrecision` to `quoteAssetPrecision`
- Add api DELETE `api/v3/openOrders`
=> Update binance api v3

cmd/configuration/flags.go, cmd/configuration/init_exchanges.go, cmd/example_config.json, cmd/main.go, common/types.go, data/fetcher/httprunner/runner_test.go, exchange/binance.go, exchange/binance/binance_endpoint.go, exchange/binance/storage/binance_postgres.go, exchange/binance/storage/binance_postgres_test.go, exchange/binance_format.go, reservesetting/cmd/main.go
* update orderbook to use market data endpoint instead of binance endpoint directly
* update lint
* remove unused code
* rename market data url and trim suffix slash
* remove unused field
* update example config
* update test http runner
=> Using market data (#1013)

apidocs/source/includes/settings/_rate_trigger_period.md, cmd/migrations/000008_create_table_general_data.down.sql, cmd/migrations/000008_create_table_general_data.up.sql, gateway/http/permission.go, gateway/http/routes_proxy.go, reservesetting/common/types.go, reservesetting/http/http.go, reservesetting/http/rate_trigger_period.go, reservesetting/storage/interface.go, reservesetting/storage/postgres/general_data.go, reservesetting/storage/postgres/general_data_test.go, reservesetting/storage/postgres/sql.go, reservesetting/storage/postgres/sql_schema.go
* add endpoint rate trigger period
=> add endpoint rate trigger period (#1014)

exchange/transport_limiter.go
* handle 429 binance status code
=> handle 429 binance status code (#1027)

common/types.go, common/universal_constant.go, core/reserve_core.go, data/fetcher/exchange.go, data/fetcher/fetcher.go, data/fetcher/fetcher_test.go, exchange/binance.go, exchange/binance_format.go, exchange/huobi_format.go, exchange/stable_ex.go
=> Add withdraw fee (#1032)

apidocs/source/includes/settings/_setting_change_main.md, cmd/migrations/000018_add_column_proposer_and_rejector.down.sql, cmd/migrations/000018_add_column_proposer_and_rejector.up.sql, reservesetting/common/types.go, reservesetting/http/setting_change.go, reservesetting/storage/interface.go, reservesetting/storage/postgres/approve_setting_change_test.go, reservesetting/storage/postgres/assets_test.go, reservesetting/storage/postgres/setting_change.go, reservesetting/storage/postgres/setting_change_test.go, reservesetting/storage/postgres/sql.go, reservesetting/storage/postgres/stable_token_params_test.go
* add column proposer and rejector
=> add column proposer and rejector (#1226)

common/types.go, core/activity_storage.go, core/reserve_core.go, core/reserve_core_test.go, data/fetcher/fetcher.go, data/fetcher/storage.go, data/storage/postgres.go, data/storage/postgres_test.go, http/http_test.go
- add org time and last time of activity
=> Update activity record 

common/types.go, core/activity_storage.go, core/reserve_core.go, core/reserve_core_test.go, data/fetcher/fetcher.go, data/fetcher/storage.go, data/storage/postgres.go, data/storage/postgres_test.go, http/http_test.go
* update activity record add org time and last time of activity
=> Update activity record  (#1243)

common/types.go, exchange/binance.go, exchange/binance/binance_endpoint.go, exchange/binance_format.go, exchange/binance_interface.go, exchange/binance_test.go
* include margin account balance in auth data
=> include margin account balance in auth data (#1238)

apidocs/source/includes/exchanges/_exchanges.md, exchange/binance/binance_endpoint.go, gateway/http/routes_proxy.go, http/server.go
* add api return  list of disabled withdraw asset
=> add api return all asset withdraw status (#1260)

blockchain/blockchain.go, cmd/example_config.json, cmd/main.go, common/bcnetwork/types.go, common/types.go, exchange/binance.go, exchange/binance/binance_endpoint.go, exchange/binance_format.go, exchange/binance_interface.go, exchange/binance_test.go, exchange/huobi.go, exchange/huobi_live.go, reservesetting/common/types.go, reservesetting/storage/postgres/postgres.go
* refactor to support alternative network (BSC)
* update binance receive deposit address with network
=> refactor to support alternative network (BSC) (#1265)

core/reserve_core.go
=> Update set rates org time (#1277)

exchange/binance.go, exchange/binance/binance_endpoint.go, exchange/binance_format.go, go.mod, go.sum
* update binance withdraw order id
=> Use customize id (#1288)

core/blockchain.go, core/reserve_core.go, core/reserve_core_test.go
- fix set block on set rate
- fix set pricing op set cancel set toAddress
=> fix minors with setrate / cancel-setrate

core/blockchain.go, core/reserve_core.go, core/reserve_core_test.go
- fix set block on set rate (#1296)
- fix set pricing op set cancel set toAddress
=> to staging

core/reserve_core.go
- fill TxTime for SetRate for override tx can work correctly
- - fix generate override tx activity id for setRate
=> fix override setRate

core/reserve_core.go
- fill TxTime for SetRate for override tx can work correctly
=> - fix generate override tx activity id for setRate (#1321)

blockchain/blockchain.go, blockchain/kn_pricing_contract.go, data/fetcher/blockchain.go, data/fetcher/fetcher.go, data/fetcher/storage.go, data/storage/postgres.go
check valid block after save to db
update init valid block duration
update
=> update check valid block duration

reservesetting/cmd/main.go, reservesetting/http/http.go, reservesetting/http/scheduled_job.go, reservesetting/scheduled-job/scheduled_job.go
* refactory scheduled job to call directly to server
=> refactory scheduled job to call directly to server (#1347)
